### ISSUE TITLE
ros.wiki.org is no longer available

### ISSUE THREAD

**Issue by mhaeberli** [PeterMitrano/WPILib_Developers_Guide#2]
Hi!

Great site, but trying to learn more about FRCSim configuration options.

ros.wiki.org is no longer getting any valid DNS response, as cited, for example, on:

http://petermitrano.github.io/WPILib_Developers_Guide/tutorials/FRCSim/Java%20Gazebo/java_gazebo.html

at:

"These are intended to behave the same as ROS_MASTER_URI and ROS_IP. info on those can be found here"

Please suggest alternative documentation.

Thanks,

Martin Haeberli

**Comment by PeterMitrano** [comment]
it's `wiki.ros.org`, good catch.
This was actually just a thing I was playing around with before I made all the screensteps docs. How did you find this? What do you think? (AKA why are you here and not on screensteps)

**Comment by mhaeberli** [comment]
Peter,
Google search ... trying to run gazebo on a separate machine from Eclipse
and from real drive station...
Screensteps seems silent on some of those configuration issues ...
I'm running Eclipse and gazebo on a quad-core Atom processor but for some
reason stuff sort of hangs up...
So I'm trying to separate concerns...
Best,
Martin

**Comment by PeterMitrano** [comment]
Oh cool. Yes, that's completely possible, and I do it very often. I didn't
realize anyone would try that. I'll make a screen-steps at some
point--hopefully you can provide some feedback.

**Comment by mhaeberli** [comment]
would love to provide feedback ...

**Comment by PeterMitrano** [comment]
I'm working on the screensteps now. I'll try to test it and put it up later this week. I'll put a link here when I'm done

**Comment by mhaeberli** [comment]
Great! Thanks!
Martin
